// <auto-generated />
using System;
using HelpDesk.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelpDesk.API.Migrations
{
    [DbContext(typeof(HelpDeskDbContext))]
    [Migration("20260626145635_AddHelpDeskEntities")]
    partial class AddHelpDeskEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("HelpDesk.API.Entities.Cliente", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("S");

                    b.Property<string>("CodClienteERP")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("DscCliente")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdEmpresa", "IdCliente");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("HelpDesk.API.Entities.Empresa", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("S");

                    b.Property<string>("Cnpj")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CodigoAcesso")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DscEmpresa")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("MensagemAtendimento")
                        .HasColumnType("longtext");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("IdEmpresa");

                    b.HasIndex("CodigoAcesso")
                        .IsUnique();

                    b.ToTable("Empresa", (string)null);
                });

            modelBuilder.Entity("HelpDesk.API.Entities.Produto", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("S");

                    b.Property<string>("DscProduto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdEmpresa", "IdProduto");

                    b.ToTable("Produto", (string)null);
                });

            modelBuilder.Entity("HelpDesk.API.Entities.ProdutoXCliente", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdProduto")
                        .HasColumnType("int");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.HasKey("IdEmpresa", "IdProduto", "IdCliente");

                    b.HasIndex("IdEmpresa", "IdCliente");

                    b.ToTable("ProdutoXCliente", (string)null);
                });

            modelBuilder.Entity("HelpDesk.API.Entities.StatusTicket", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdStatusTicket")
                        .HasColumnType("int");

                    b.Property<string>("DscStatusTicket")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("TipoTicket")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("IdEmpresa", "IdStatusTicket");

                    b.ToTable("StatusTicket", (string)null);
                });

            modelBuilder.Entity("HelpDesk.API.Entities.Tecnico", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdTecnico")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NotificarNovosChamados")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("N");

                    b.HasKey("IdEmpresa", "IdTecnico");

                    b.HasIndex("IdEmpresa", "IdUsuario");

                    b.ToTable("Tecnico", (string)null);
                });

            modelBuilder.Entity("HelpDesk.API.Entities.Ticket", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdTicket")
                        .HasColumnType("int");

                    b.Property<string>("Assunto")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("DscTicket")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DtHrAbertura")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DtHrFinalizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdStatusTicket")
                        .HasColumnType("int");

                    b.Property<int?>("IdTecnicoFinalizacao")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoOcorrencia")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("Normal");

                    b.Property<string>("TicketCancelado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("N");

                    b.HasKey("IdEmpresa", "IdTicket");

                    b.HasIndex("IdEmpresa", "DtHrAbertura");

                    b.HasIndex("IdEmpresa", "IdCliente");

                    b.HasIndex("IdEmpresa", "IdStatusTicket");

                    b.HasIndex("IdEmpresa", "IdTecnicoFinalizacao");

                    b.HasIndex("IdEmpresa", "IdTipoOcorrencia");

                    b.HasIndex("IdEmpresa", "IdUsuario");

                    b.ToTable("Ticket", (string)null);
                });

            modelBuilder.Entity("HelpDesk.API.Entities.TicketDocumento", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdTicketDocumento")
                        .HasColumnType("int");

                    b.Property<string>("CaminhoArquivo")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("DtHrUpload")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdTicket")
                        .HasColumnType("int");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<long?>("TamanhoBytes")
                        .HasColumnType("bigint");

                    b.HasKey("IdEmpresa", "IdTicketDocumento");

                    b.HasIndex("IdEmpresa", "IdTicket");

                    b.ToTable("TicketDocumento", (string)null);
                });

            modelBuilder.Entity("HelpDesk.API.Entities.TicketInteracao", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdTicketInteracao")
                        .HasColumnType("int");

                    b.Property<string>("AguardarInteracaoUsuario")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("N");

                    b.Property<string>("DscInteracao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DtHrInteracao")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("IdTecnico")
                        .HasColumnType("int");

                    b.Property<int>("IdTicket")
                        .HasColumnType("int");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Privativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("N");

                    b.HasKey("IdEmpresa", "IdTicketInteracao");

                    b.HasIndex("IdEmpresa", "IdTecnico");

                    b.HasIndex("IdEmpresa", "IdTicket");

                    b.HasIndex("IdEmpresa", "IdUsuario");

                    b.ToTable("TicketInteracao", (string)null);
                });

            modelBuilder.Entity("HelpDesk.API.Entities.TipoOcorrencia", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdTipoOcorrencia")
                        .HasColumnType("int");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("S");

                    b.Property<string>("DscTipoOcorrencia")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("EmailCopiaChamado")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("FiltroChamado")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("IdEmpresa", "IdTipoOcorrencia");

                    b.ToTable("TipoOcorrencia", (string)null);
                });

            modelBuilder.Entity("HelpDesk.API.Entities.Usuario", b =>
                {
                    b.Property<int>("IdEmpresa")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Ativo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("S");

                    b.Property<string>("EhAdm")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(1)
                        .HasColumnType("varchar(1)")
                        .HasDefaultValue("N");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("NomeCompleto")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("IdEmpresa", "IdUsuario");

                    b.HasIndex("IdEmpresa", "IdCliente");

                    b.HasIndex("IdEmpresa", "NomeUsuario")
                        .IsUnique();

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("HelpDesk.API.Entities.Cliente", b =>
                {
                    b.HasOne("HelpDesk.API.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("HelpDesk.API.Entities.Produto", b =>
                {
                    b.HasOne("HelpDesk.API.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("HelpDesk.API.Entities.ProdutoXCliente", b =>
                {
                    b.HasOne("HelpDesk.API.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDesk.API.Entities.Cliente", "Cliente")
                        .WithMany("ProdutosXCliente")
                        .HasForeignKey("IdEmpresa", "IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDesk.API.Entities.Produto", "Produto")
                        .WithMany("ClientesXProduto")
                        .HasForeignKey("IdEmpresa", "IdProduto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empresa");

                    b.Navigation("Produto");
                });

            modelBuilder.Entity("HelpDesk.API.Entities.StatusTicket", b =>
                {
                    b.HasOne("HelpDesk.API.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("HelpDesk.API.Entities.Tecnico", b =>
                {
                    b.HasOne("HelpDesk.API.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDesk.API.Entities.Usuario", "Usuario")
                        .WithMany("Tecnicos")
                        .HasForeignKey("IdEmpresa", "IdUsuario");

                    b.Navigation("Empresa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HelpDesk.API.Entities.Ticket", b =>
                {
                    b.HasOne("HelpDesk.API.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDesk.API.Entities.Cliente", "Cliente")
                        .WithMany("Tickets")
                        .HasForeignKey("IdEmpresa", "IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDesk.API.Entities.StatusTicket", "StatusTicket")
                        .WithMany("Tickets")
                        .HasForeignKey("IdEmpresa", "IdStatusTicket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDesk.API.Entities.Tecnico", "TecnicoFinalizacao")
                        .WithMany()
                        .HasForeignKey("IdEmpresa", "IdTecnicoFinalizacao");

                    b.HasOne("HelpDesk.API.Entities.TipoOcorrencia", "TipoOcorrencia")
                        .WithMany("Tickets")
                        .HasForeignKey("IdEmpresa", "IdTipoOcorrencia")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDesk.API.Entities.Usuario", "Usuario")
                        .WithMany("TicketsAbertos")
                        .HasForeignKey("IdEmpresa", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Empresa");

                    b.Navigation("StatusTicket");

                    b.Navigation("TecnicoFinalizacao");

                    b.Navigation("TipoOcorrencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HelpDesk.API.Entities.TicketDocumento", b =>
                {
                    b.HasOne("HelpDesk.API.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDesk.API.Entities.Ticket", "Ticket")
                        .WithMany("Documentos")
                        .HasForeignKey("IdEmpresa", "IdTicket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("HelpDesk.API.Entities.TicketInteracao", b =>
                {
                    b.HasOne("HelpDesk.API.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDesk.API.Entities.Tecnico", "Tecnico")
                        .WithMany()
                        .HasForeignKey("IdEmpresa", "IdTecnico");

                    b.HasOne("HelpDesk.API.Entities.Ticket", "Ticket")
                        .WithMany("Interacoes")
                        .HasForeignKey("IdEmpresa", "IdTicket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDesk.API.Entities.Usuario", "Usuario")
                        .WithMany("Interacoes")
                        .HasForeignKey("IdEmpresa", "IdUsuario");

                    b.Navigation("Empresa");

                    b.Navigation("Tecnico");

                    b.Navigation("Ticket");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("HelpDesk.API.Entities.TipoOcorrencia", b =>
                {
                    b.HasOne("HelpDesk.API.Entities.Empresa", "Empresa")
                        .WithMany()
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("HelpDesk.API.Entities.Usuario", b =>
                {
                    b.HasOne("HelpDesk.API.Entities.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEmpresa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDesk.API.Entities.Cliente", "Cliente")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdEmpresa", "IdCliente");

                    b.Navigation("Cliente");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("HelpDesk.API.Entities.Cliente", b =>
                {
                    b.Navigation("ProdutosXCliente");

                    b.Navigation("Tickets");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("HelpDesk.API.Entities.Empresa", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("HelpDesk.API.Entities.Produto", b =>
                {
                    b.Navigation("ClientesXProduto");
                });

            modelBuilder.Entity("HelpDesk.API.Entities.StatusTicket", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("HelpDesk.API.Entities.Ticket", b =>
                {
                    b.Navigation("Documentos");

                    b.Navigation("Interacoes");
                });

            modelBuilder.Entity("HelpDesk.API.Entities.TipoOcorrencia", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("HelpDesk.API.Entities.Usuario", b =>
                {
                    b.Navigation("Interacoes");

                    b.Navigation("Tecnicos");

                    b.Navigation("TicketsAbertos");
                });
#pragma warning restore 612, 618
        }
    }
}
